name: Automatically Build Windows Binary (cgo) on any change

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'lib/**'
      - '*.go'
      - 'go.*'
  pull_request:
    branches: [ master ]
    paths:
      - 'lib/**'
      - '*.go'
      - 'go.*'
      
jobs:
  build-windows:
    runs-on: windows-latest

    env:
      CGO_ENABLED: 1
      GOOS: windows
      GOARCH: amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Build Windows binary with cgo
        run: go build -v -o offline_logi_flow_sim.exe ./...

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          default_bump: patch

      - name: Create GitHub Draft Release
        id: create_draft_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Snapshot ${{ steps.tag_version.outputs.new_tag }}
          draft: true
          body: |
            Automated snapshot for ${{ steps.tag_version.outputs.new_tag }}
          files: offline_logi_flow_sim.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
