name: Build and release Windows Binary (cgo)

on:
  workflow_dispatch:
      
jobs:
  build-windows:
    runs-on: windows-latest

    env:
      CGO_ENABLED: 1
      GOOS: windows
      GOARCH: amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Build Windows binary with cgo
        run: go build -v -o offline_logi_flow_sim.exe ./...

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          default_bump: patch

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          draft: false
          body: |
            Automated release for ${{ steps.tag_version.outputs.new_tag }}
          files: offline_logi_flow_sim.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
